branches:
  only:
  - master
language: node_js
node_js:
- lts/*
git:
  depth: 30
install:
- yarn --frozen-lockfile
- yarn test
script:
- "./build.sh"
after_script:
- "./notify.sh"
cache: yarn
deploy:
  matrix:
  - provider: pages
    local-dir: docs
    github-token: "$GITHUB_TOKEN"
    skip-cleanup: true
    keep-history: true
    on:
      branch: main
  - provider: npm
    email: 873610008@qq.com
    api_key: "$NPM_TOKEN"
    skip-cleanup: true
    on:
      branch: master
